typedef struct Conversions {
    bool active;
    f64 y, y_to;
    
    int timer;
    
    int definition;
    Uint8 definition_alpha;
    
    bool holding_scroll_bar;
    SDL_Rect scroll_bar_full, scroll_bar;
    int max_height;
} Conversions;


#define CELL_ANY_STONE -1
#define CELL_ANY_COAL  -2

int conversions[] = {
    // Converter,  Fuel, Input 1, Input 2, Output
    CONVERTER_FUEL, 0,   CELL_MARBLE,    0, CELL_UNREFINED_COAL,
    CONVERTER_FUEL, 0,   CELL_STONE,     0, CELL_UNREFINED_COAL,
    CONVERTER_FUEL, 0,   CELL_SANDSTONE, 0, CELL_UNREFINED_COAL,
    CONVERTER_FUEL, 0,   CELL_DIRT,      0, CELL_UNREFINED_COAL,
    CONVERTER_FUEL, 0,   CELL_SAND,      0, CELL_UNREFINED_COAL,
    CONVERTER_FUEL, 0,   CELL_UNREFINED_COAL, CELL_GLASS,  CELL_REFINED_COAL,
    CONVERTER_FUEL, 0,   CELL_ANY_STONE, CELL_REFINED_COAL, CELL_LAVA, // TODO: Any stone.
    
    CONVERTER_MATERIAL, 0,    CELL_STEAM,    0, CELL_WATER,
    CONVERTER_MATERIAL, 0,    CELL_WATER,    0, CELL_ICE,
    
    CONVERTER_MATERIAL, CELL_UNREFINED_COAL, CELL_STONE, 0, CELL_MARBLE,
    CONVERTER_MATERIAL, CELL_UNREFINED_COAL, CELL_SAND, 0, CELL_GLASS,
    CONVERTER_MATERIAL, CELL_UNREFINED_COAL, CELL_DIRT, 0, CELL_STONE,
    CONVERTER_MATERIAL, CELL_UNREFINED_COAL, CELL_STONE, CELL_SAND, CELL_SANDSTONE,
    CONVERTER_MATERIAL, CELL_UNREFINED_COAL, CELL_ICE, 0, CELL_WATER,
    CONVERTER_MATERIAL, CELL_UNREFINED_COAL, CELL_WATER, 0, CELL_STEAM,
    
    CONVERTER_MATERIAL, CELL_REFINED_COAL, CELL_STONE, 0, CELL_MARBLE,
    CONVERTER_MATERIAL, CELL_REFINED_COAL, CELL_SANDSTONE, CELL_MARBLE, CELL_QUARTZ,
    CONVERTER_MATERIAL, CELL_REFINED_COAL, CELL_DIRT, 0, CELL_STONE,
    CONVERTER_MATERIAL, CELL_REFINED_COAL, CELL_ICE, 0, CELL_STEAM,
    
    CONVERTER_MATERIAL, CELL_LAVA, CELL_STONE, 0, CELL_MARBLE,
    CONVERTER_MATERIAL, CELL_LAVA, CELL_ANY_COAL, 0, CELL_BASALT, // TODO: Any coal
    CONVERTER_MATERIAL, CELL_LAVA, CELL_QUARTZ, CELL_MARBLE, CELL_GRANITE,
    CONVERTER_MATERIAL, CELL_LAVA, CELL_BASALT, CELL_GRANITE, CELL_DIAMOND,
};

void converter_gui_draw(int target);